#!/usr/bin/env python3
"""Produce a structurally complete build from a randomly-initialised toy model.

Purpose: let anyone open the front end and click through a real collision
without first owning a GPU or downloading weights. The layout, the graph, the
pair cards, the bridge panels are all genuine outputs of the real pipeline.

The *semantics* are not real — the model has random weights. Every artifact
this writes carries `meta.provenance`, and the front end turns that into a red
banner, so the demo can never be mistaken for a result.

    python scripts/make_smoke_build.py            # -> web/data/graph.json

Replace it with the real thing as soon as you can run extraction:

    python -m collider all --config configs/qwen3-1.7b-4bit.yaml
"""

from __future__ import annotations

import json
import logging
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "src"), str(ROOT / "tests")]

from collider.config import Config           # noqa: E402
from collider.pipeline import stage_build    # noqa: E402
from collider.schema import ConceptSet       # noqa: E402
from smoke_model import make_smoke_encoder   # noqa: E402

PROVENANCE = (
    "Generated by scripts/make_smoke_build.py from a randomly-initialised "
    "6-layer toy model with no trained weights."
)


def main() -> int:
    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(message)s")
    cfg = Config(
        concepts=str(ROOT / "data" / "concepts" / "seed_concepts.jsonl"),
        build_dir=str(ROOT / "data" / "build"),
        web_data_dir=str(ROOT / "web" / "data"),
        # 64-dim toy vectors: nothing to reduce, and the top-8 PCA removal of
        # the default would take out an eighth of the space.
        remove_top_k=2,
        reduced_dim=64,
        knn_k=12,
        n_pairs=40,
        n_candidates=4000,
        layout="pca",
    )
    concepts = ConceptSet.from_jsonl(cfg.concepts)
    encoder = make_smoke_encoder(concepts, batch_size=16, layer=4)
    vs = encoder.encode(concepts)
    vs.meta["provenance"] = PROVENANCE
    vs.meta["config"] = cfg.to_dict()
    vs.save(cfg.build_dir)

    stage_build(cfg)

    # stage_build rebuilds meta from the stored vector meta, but be explicit:
    # the provenance stamp must survive into what the browser loads.
    for path in (Path(cfg.build_dir) / "graph.json", Path(cfg.web_data_dir) / "graph.json"):
        payload = json.loads(path.read_text(encoding="utf-8"))
        payload["meta"]["provenance"] = PROVENANCE
        path.write_text(json.dumps(payload, ensure_ascii=False), encoding="utf-8")

    print("\nSmoke build written. Serve it with:  python -m collider serve")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
