"""Structural signatures: the second space, and the one that finds analogies.

The problem this solves
-----------------------
The rest of this project measures similarity between concept *definitions*. That
is a **topical** measure, and topicality is close to the opposite of what
cross-domain analogy needs.

`immune memory` and `caching` are the same structure — pay once, store the
result, answer the repeat instantly, fail when the stored key goes stale. Their
definitions share almost no vocabulary, so definition embeddings place them far
apart. The collider then treats them as a "distant pair" and asks the user to go
looking for a bridge, when in fact they are the *same thing* and should have
been neighbours.

So searching the distant tail for analogies is searching in the wrong place with
the wrong instrument. The fix is not a better distance metric. It is to **change
what gets embedded.**

The move
--------
For each concept, write a *structural signature*: what it is, with the
vocabulary of its field removed. Not "plants", "money", "genes", "notes" — only
mechanism, driver, constraint, and failure mode. Two concepts with the same
underlying structure then share most of their signature words, and ordinary
cosine puts them next to each other.

This turns a hard problem (find distant-but-analogous pairs in a tail dominated
by incoherent pairs) into an easy one (nearest-neighbour lookup).

Two spaces, two axes
--------------------
Keep both vectors per concept and the interesting quantity becomes a
*difference*:

    structurally near  +  topically far   =  a live cross-domain analogy
    structurally near  +  topically near  =  two names for the same local idea
    structurally far   +  topically near  =  same subject, unrelated mechanism
    structurally far   +  topically far   =  nothing

`analogy_score` is exactly the top-left cell. It replaces the five-feature
heuristic in `pairs.py` for this purpose — not because that heuristic is wrong,
but because it was a set of proxies for a thing that can now be measured
directly.

Scaling
-------
Signatures are generated by an LLM against a fixed template
(`scripts/generate_structures.py`). That is the one place a *large* model earns
its cost: writing the signature needs real world knowledge, but it happens once
per concept, offline, and the result is cached as text you can read and correct
by hand. Everything downstream runs on the small local model.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable

import numpy as np

from .encoders.base import Template
from .schema import Concept, ConceptSet, VectorSet

# The signature is embedded WITHOUT the concept's label. This matters: the label
# is the single most domain-loaded token available ("photosynthesis" drags the
# whole of biology with it), and including it would reintroduce exactly the
# topical signal the signature exists to strip out.
STRUCTURE_TEMPLATES: tuple[Template, ...] = (
    Template("structure_bare", "{definition}", span="definition"),
    Template("structure_framed", "Structure: {definition}", span="definition"),
)

# The template the generator fills in. Kept here rather than in the script so the
# contract between "what we asked for" and "what we embed" lives in one file.
SIGNATURE_INSTRUCTION = """\
Describe the ABSTRACT STRUCTURE of the concept below, so that a reader who knows
nothing about its field could recognise the same structure elsewhere.

Hard rule: do not use any word that names or implies the field. No domain nouns,
no jargon, no examples from the field. If you cannot say it without them, you
have not abstracted far enough.

Cover, in two or three sentences: the mechanism (what acts on what, and with what
effect); what drives it or what it is limited by; and how it characteristically
fails.

Concept: {label}
Field: {domain}
Definition: {definition}

Structure:"""


def load_structures(path: str | Path) -> dict[str, str]:
    """Read `{"id": ..., "structure": ...}` lines into a mapping."""
    out: dict[str, str] = {}
    with open(path, "r", encoding="utf-8") as fh:
        for lineno, line in enumerate(fh, 1):
            line = line.strip()
            if not line or line.startswith("//"):
                continue
            try:
                row = json.loads(line)
                out[row["id"]] = " ".join(row["structure"].split())
            except Exception as exc:  # noqa: BLE001 - want the line number
                raise ValueError(f"{path}:{lineno}: {exc}") from exc
    return out


def as_concept_set(concepts: ConceptSet, structures: dict[str, str]) -> ConceptSet:
    """A parallel ConceptSet whose `definition` is the structural signature.

    Row order is preserved exactly, so the resulting vectors stay aligned with
    the topical vectors and with everything else in the build. A concept with no
    signature keeps its definition and is flagged in `meta`, so a partial
    signature file degrades rather than crashes — but check the count, because
    an unflagged fallback silently reintroduces topical signal for that row.
    """
    rows = []
    for c in concepts:
        sig = structures.get(c.id)
        rows.append(Concept(
            id=c.id,
            label=c.label,
            definition=sig or c.definition,
            domain=c.domain,
            meta={"has_structure": sig is not None},
        ))
    return ConceptSet(rows)


def missing_structures(concepts: ConceptSet, structures: dict[str, str]) -> list[str]:
    return [c.id for c in concepts if c.id not in structures]


def leaked_vocabulary(
    concepts: ConceptSet, structures: dict[str, str], min_len: int = 5
) -> dict[str, list[str]]:
    """Words from a concept's own label or domain that survived into its signature.

    A cheap automatic check on the one rule that makes this work. It cannot catch
    a signature that is domain-specific without reusing the label's exact words,
    so treat a clean result as necessary but not sufficient.
    """
    leaks: dict[str, list[str]] = {}
    for c in concepts:
        sig = structures.get(c.id)
        if not sig:
            continue
        low = sig.lower()
        banned = {w for w in (c.label.lower().split() + [c.domain.lower()])
                  if len(w) >= min_len}
        hits = sorted(w for w in banned if w in low)
        if hits:
            leaks[c.id] = hits
    return leaks


@dataclass
class DualSpace:
    """Topical and structural vectors for the same, identically ordered concepts."""

    topical: np.ndarray      # (N, D) L2-normalised
    structural: np.ndarray   # (N, D') L2-normalised
    concept_ids: list[str]

    def __post_init__(self) -> None:
        if self.topical.shape[0] != self.structural.shape[0]:
            raise ValueError("topical and structural vectors have different row counts")
        if len(self.concept_ids) != self.topical.shape[0]:
            raise ValueError("concept_ids does not match vector row count")

    @classmethod
    def from_vectorsets(cls, topical: VectorSet, structural: VectorSet) -> "DualSpace":
        if topical.concept_ids != structural.concept_ids:
            raise ValueError(
                "the two vector sets are not row-aligned. Both must be built from "
                "the same concept file, in the same order."
            )
        return cls(topical.vectors, structural.vectors, list(topical.concept_ids))

    # ------------------------------------------------------------ the score

    def analogy_score(self, alpha: float = 1.0) -> np.ndarray:
        """(N, N) matrix of `structural_similarity - alpha * topical_similarity`.

        `alpha` is the dial between two different questions:

        * `alpha = 0` — "what is structurally like this?" Returns same-field
          restatements alongside genuine cross-field matches.
        * `alpha = 1` — "what is structurally like this but *not about the same
          thing*?" This is the cross-domain analogy finder, and the default.
        * `alpha > 1` — aggressively penalises any topical overlap. Surfaces
          stranger pairs and more noise.

        Note this is a *relative* score. It is meaningful for ranking within a
        row and meaningless as an absolute number, because the two spaces have
        different similarity distributions.
        """
        s = self.structural @ self.structural.T
        t = self.topical @ self.topical.T
        score = s - alpha * t
        np.fill_diagonal(score, -np.inf)
        return score

    def top_analogies(
        self, n: int = 50, alpha: float = 1.0, max_per_concept: int = 3
    ) -> list[dict[str, Any]]:
        """Highest-scoring pairs overall, with a per-concept cap for diversity.

        The cap matters: a handful of very abstract concepts (`feedback loop`,
        `invariant`) are structurally close to almost everything and will
        otherwise fill the entire list.
        """
        score = self.analogy_score(alpha)
        iu = np.triu_indices_from(score, k=1)
        flat = score[iu]
        order = np.argsort(-flat)

        s = self.structural @ self.structural.T
        t = self.topical @ self.topical.T

        chosen: list[dict[str, Any]] = []
        used: dict[int, int] = {}
        for k in order:
            if len(chosen) >= n:
                break
            i, j = int(iu[0][k]), int(iu[1][k])
            if used.get(i, 0) >= max_per_concept or used.get(j, 0) >= max_per_concept:
                continue
            used[i] = used.get(i, 0) + 1
            used[j] = used.get(j, 0) + 1
            chosen.append({
                "a": self.concept_ids[i], "b": self.concept_ids[j],
                "a_idx": i, "b_idx": j,
                "score": float(flat[k]),
                "structural_similarity": float(s[i, j]),
                "topical_similarity": float(t[i, j]),
            })
        return chosen

    def rank_of(self, anchor: int, target: int, alpha: float = 1.0) -> int:
        """1-based rank of `target` in `anchor`'s analogy ranking. Lower is better."""
        row = self.analogy_score(alpha)[anchor]
        return int((row > row[target]).sum()) + 1
